name: Feature request
description: Suggest an idea for bevy-mpm
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Have an idea that would make bevy-mpm better? Let us know!

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: I'm frustrated when…
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
      placeholder: I'd love it if…
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Have you looked at other approaches?

  - type: textarea
    id: notes
    attributes:
      label: Additional context
      placeholder: Mockups, sketches, links, etc.
